### ISSUE TITLE
Pagamento com cartão não brasileiro

### ISSUE THREAD

**Issue by rodolphoeck** [pythonbrasil/pythonbrasil13-site#3]
Já enviei esse feedback pro Cássio também.

Tentei realizar minha inscrição, mas todo o processo de inscrição é "Brasil-centric". As informações ou os formatos para pagamento com cartão nem sempre se aplicam para pessoas fora do Brasil (CEP, CPF, telefone etc.).

Como faz pagamento com cartão não brasileiro?

Nos anos anteriores foi feito one-off com PayPal. Seria bom se desse para consertar isso de uma vez por todas para não ter esse problema todo ano para se cadastrar no evento.

Abraços e obrigado!

**Comment by igr-santos** [comment]
@rodolphoeck foi adicionado a opção por PayPal
