### ISSUE TITLE
Problema ao compilar o sistema

### ISSUE THREAD

**Issue by rennerocha** [pythonbrasil/pythonbrasil13-site#9]
Como a solução com Docker não funcionou, tentei seguir o passo-a-passo com virtualenv. Mas as instruções fornecidas também não funcionaram:

```
(pythonbrasil13) renne@capivara:pythonbrasil13-site$ make html serve
cd theme; make all
make[1]: Entering directory '/home/renne/projects/pythonbrasil13-site/theme'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/renne/projects/pythonbrasil13-site/theme'
pelican /home/renne/projects/pythonbrasil13-site/content -o /home/renne/projects/pythonbrasil13-site/output -s /home/renne/projects/pythonbrasil13-site/pelicanconf.py 
CRITICAL: KeyError: 'JINJA_EXTENSIONS'
Makefile:48: recipe for target 'html' failed
make: *** [html] Error 1
(pythonbrasil13) renne@capivara:pythonbrasil13-site$ 
```

**Comment by rennerocha** [comment]
Aparentemente algum plugin do pelican não funciona direito com a versão 3.7

https://github.com/AlexJF/pelican-advthumbnailer/issues/5

Eu mudei para a 3.6 no meu ambiente de desenvolvimento e tudo funcionou. Porém não alterei no requirements.txt pois não sei qual o plugin está com problema e se ele realmente é necessário funcionar com a versão 3.7 .

**Comment by semente** [comment]
valeu @rennerocha, vou fazer isso.

@igr-santos na sua máquina vc ta rodando qual versão?

**Comment by ramiroluz** [comment]
Também tive esse problema, também funcionou fixar a versão do pelican para 3.6.
